cmake_minimum_required(VERSION 3.20)
# ======================================================
# Generated by: vix install
# DO NOT EDIT MANUALLY
# ======================================================

set(_VIX_DEPS_DIR "/home/softadastra/vixcpp/kv/.vix/deps")

# softadastra/core @1.4.0 (ab087d56af5fc585d063e4b0c2dc91a800c06917)
if(NOT TARGET softadastra::core)
  add_subdirectory("/home/softadastra/vixcpp/kv/.vix/deps/softadastra.core" "/home/softadastra/vixcpp/kv/.vix/_vix_build_softadastra.core")
endif()
if(NOT TARGET softadastra::core)
  message(FATAL_ERROR "Dependency softadastra/core did not define expected target softadastra::core")
endif()

# softadastra/fs @1.8.0 (75c87ffdbc9e3e0ad51afce4a4bde7df8faf9da6)
if(NOT TARGET softadastra::fs)
  add_subdirectory("/home/softadastra/vixcpp/kv/.vix/deps/softadastra.fs" "/home/softadastra/vixcpp/kv/.vix/_vix_build_softadastra.fs")
endif()
if(NOT TARGET softadastra::fs)
  message(FATAL_ERROR "Dependency softadastra/fs did not define expected target softadastra::fs")
endif()

# softadastra/wal @0.8.0 (6a65f39f7e7e4ffd7e539a962a28b09b067dfbcc)
if(NOT TARGET softadastra::wal)
  add_subdirectory("/home/softadastra/vixcpp/kv/.vix/deps/softadastra.wal" "/home/softadastra/vixcpp/kv/.vix/_vix_build_softadastra.wal")
endif()
if(NOT TARGET softadastra::wal)
  message(FATAL_ERROR "Dependency softadastra/wal did not define expected target softadastra::wal")
endif()

# softadastra/store @0.7.1 (74d20f6df00c2607e9b401e2158b39abe44763cc)
if(NOT TARGET softadastra::store)
  add_subdirectory("/home/softadastra/vixcpp/kv/.vix/deps/softadastra.store" "/home/softadastra/vixcpp/kv/.vix/_vix_build_softadastra.store")
endif()
if(NOT TARGET softadastra::store)
  message(FATAL_ERROR "Dependency softadastra/store did not define expected target softadastra::store")
endif()

